"module: copilot":
  - '(自动作战|自动战斗|自动编队|作业)'
  - '(copilot)'
  - '(作業|自動戰鬥)'
  - '(自動戦闘)'
"module: GUI":
  - '(图形化界面|闪退)'
  - '(gui|GUI|crash)'
  - '(介面)'
  - '(画面|インターフェース)'
"module: fight":
  - '(刷图|刷.{0,6}材料)'
"module: infrast":
  - '(基建|贸易站|制造站|控制中枢|会客室)'
  - '(infrast|base)'
  - '(基地)'
"module: others":
  - '(信用|拜访|登录|开始唤醒)'
"module: recruit":
  - '(公招|公开招募)'
  - '(recruit)'
  - '(公開求人)'
"module: roguelike":
  - '(肉鸽|集成战略)'
  - '(rogue)'
  - '(肉鴿)'
  - '(ローグ)'
"release":
  - '(Release v(\d)+\.(\d)+\.(\d)+)'
