customadbaddress: ""
cron: "0 0 */2 * * *"
fight:
  stage: LastBattle
  medicine: 999
  stone: 0
  times: 999
infrast:
  mode: 1
  orders:
  - Mfg
  - Trade
  - Control
  - Power
  - Reception
  - Office
  - Dorm
  drones: Money
  threshold: 0.3
recruit:
  max: 3
  selects:
  - 3
  - 4
  - 5
  confirms:
  - 3
  - 4
  - 5
  refresh: true
mall:
  buy: true
