name: dev-build-mac

on:
  push:
    branches-ignore:
      - master
    paths:
      - 'src/MeoAssistant/**'
      - 'src/MeoAsstGui/**'
      - 'src/MeoAsstMac/**'
      - '3rdparty/**'
      - 'include/**'
      - 'resource/**'
      - CMakeLists.txt
  pull_request:
    branches:
      - dev
    paths:
      - 'src/MeoAssistant/**'
      - 'src/MeoAsstGui/**'
      - 'src/MeoAsstMac/**'
      - '3rdparty/**'
      - 'include/**'
      - 'resource/**'
      - CMakeLists.txt

jobs:
  macos-latest:
    runs-on: macos-12
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: recursive
      - name: Cache Homebrew
        uses: actions/cache@v3
        with:
          path: $(brew --prefix)
          key: ${{ runner.os }}-homebrew-${{ hashFiles('.config/brew/Brewfile') }}
      - name: Install Dependencies
        run: |
          brew update --preinstall
          brew install ninja range-v3
      - name: Configure MeoAssistant
        run: |
          mkdir build && cd build
          cmake .. -GNinja -DBUILD_XCFRAMEWORK=ON -DBUILD_UNIVERSAL=ON
      - name: Build libMeoAssistant
        run: cmake --build build
      - name: Build MeoAsstMac
        working-directory: src/MeoAsstMac
        run: xcodebuild ARCHS="arm64 x86_64" CODE_SIGN_IDENTITY="-" DEVELOPMENT_TEAM="-" ONLY_ACTIVE_ARCH=NO -derivedDataPath DerivedData -project MeoAsstMac.xcodeproj -scheme MeoAsstMac
      - uses: actions/upload-artifact@v1
        with:
          name: MAA-macOS
          path: src/MeoAsstMac/DerivedData/Build/Products/Debug
