name: "Maa Dev Build"

on:
  push:
    branches:
      - master
  pull_request:
  workflow_dispatch:

jobs:
  build:

    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup .NET 6.0.x
        uses: actions/setup-dotnet@v2
        with:
          dotnet-version: 6.0.x

      - name: Run dev build task
        run: pwsh .\build.ps1 DevBuild

      - name: Upload Artifacts Release
        uses: actions/upload-artifact@v3
        with:
          name: MaaFull-DevBuild-Release
          path: ./artifacts/MaaFull-DevBuild-Release*

      - name: Upload Artifacts RelWithDebInfo
        uses: actions/upload-artifact@v3
        with:
          name: MaaFull-DevBuild-RelWithDebInfo
          path: ./artifacts/MaaFull-DevBuild-RelWithDebInfo*

      - name: Upload Artifacts CICD
        uses: actions/upload-artifact@v3
        with:
          name: MaaFull-DevBuild-CICD
          path: ./artifacts/MaaFull-DevBuild-CICD*
