name: release-ota

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      limit:
        description: 'Number of releases to fetch, 2 at least'
        required: false
        default: 51
        type: number

jobs:
  make-ota:
    runs-on: "ubuntu-latest"
    steps:
      - uses: actions/checkout@v3
      - name: "Fetch release info"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -pv build-ota && cd build-ota
          gh release list --repo 'MaaAssistantArknights/MaaAssistantArknights' --limit ${{ inputs.limit || 51 }} | tee ./release_list.txt
          echo "prerelease=$([ $(head -n 1 release_list.txt | awk '{ print $2}') = 'Pre-release' ] || echo false && echo true)" >> $GITHUB_ENV
          cat ./release_list.txt | awk '{ print $1 }' > ./releases
          echo "release_tag=$(head -n 1 ./releases)" >> $GITHUB_ENV
      - name: "Build OTA"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build-ota
          ../tools/OTAPacker/build.sh 'MaaAssistantArknights/MaaAssistantArknights' ./releases
      - name: "Upload to MaaRelease"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: ${{ format('{0}/{1}', github.repository_owner, 'MaaRelease') }}
          repo_token: ${{ secrets.MAARELEASE_RELEASE }}
          file_glob: true
          file: build-ota/*.zip
          tag: ${{ env.release_tag }}
          prerelease: ${{ env.prerelease }}
          overwrite: true

