name: release-ota

on:
  release:
    types: [published]
  workflow_dispatch:
    inputs:
      limit:
        description: 'Number of releases to fetch, 2 at least'
        required: false
        default: 51
        type: number

jobs:
  make-ota:
    runs-on: "ubuntu-latest"
    steps:
      - name: "Fetch MaaRelease"
        uses: actions/checkout@v3
        with:
          repository: ${{ format('{0}/{1}', github.repository_owner, 'MaaRelease') }}
          path: MaaRelease
          fetch-depth: 0
          token: ${{ secrets.MAARELEASE_RELEASE }}
      - uses: actions/checkout@v3
        with:
          path: MaaAssistantArknights
      - name: "Fetch release info"
        env: 
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          mkdir -pv build-ota && cd build-ota
          gh release list --repo 'MaaAssistantArknights/MaaAssistantArknights' --limit ${{ inputs.limit || 51 }} | tee ./release_list.txt
          echo "prerelease=$([ $(head -n 1 release_list.txt | awk '{ print $2}') = 'Pre-release' ] && echo true || echo false)" >> $GITHUB_ENV
          cat ./release_list.txt | awk '{ print $1 }' > ./releases
          echo "release_tag=$(head -n 1 ./releases)" >> $GITHUB_ENV
      - name: "Build OTA"
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          cd build-ota
          $GITHUB_WORKSPACE/MaaAssistantArknights/tools/OTAPacker/build.sh 'MaaAssistantArknights/MaaAssistantArknights' ./releases
      - name: "Commit and setup tag"
        run: |
          cd MaaRelease
          git config user.name 'github-actions[bot]'
          git config user.email 'github-actions[bot]@users.noreply.github.com'
          git checkout --orphan temp
          git rm -rf .
          git commit --allow-empty --message ${{ env.release_tag }}
          git tag ${{ env.release_tag }} || exit 0 # do nothing if the tag already exists
          git push --tags $PUSH_REMOTE
        env:
          PUSH_REMOTE: https://github-actions[bot]:${{ secrets.MAARELEASE_RELEASE }}@github.com/${{ github.repository_owner }}/MaaRelease
      - name: "Upload to MaaRelease"
        uses: svenstaro/upload-release-action@v2
        with:
          repo_name: ${{ format('{0}/{1}', github.repository_owner, 'MaaRelease') }}
          repo_token: ${{ secrets.MAARELEASE_RELEASE }}
          file_glob: true
          file: build-ota/*.zip
          tag: ${{ env.release_tag }}
          prerelease: ${{ env.prerelease }}
          overwrite: true

